services:
  gusto2-backend:
    build: ./backend
    container_name: gusto2-backend
    ports:
      - "8000:8000"
    restart: always
    networks:
      - gusto2-network
    volumes:
      - ./backend:/app
      - ${DATA_VOLUME:-./data}:/app/data
    environment:
      - NOTION_API_TOKEN=${NOTION_API_TOKEN}
      - NOTION_MEALPLAN_PAGE_ID=${NOTION_MEALPLAN_PAGE_ID}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}

  gusto2-frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: gusto2-frontend
    ports:
      - "8080:8080"
    depends_on:
      - gusto2-backend
    networks:
      - gusto2-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - frontend_cache:/app/node_modules/.cache
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  gusto2-network:
    driver: bridge

volumes:
  frontend_cache:
