FROM node:16-alpine

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Create cache directory and make sure node has proper permissions
RUN mkdir -p /app/node_modules/.cache && chmod -R 777 /app/node_modules/.cache

# Expose port 8080 for the dev server
EXPOSE 8080

# Start the development server with hot-reload
CMD ["npm", "run", "serve"]